import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Kuluçka Stalker
        </h1>

        <div className={styles.grid}>
          <Link href="/login" className={styles.card}>
            <h2>Login &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Link>

          <Link href="/register" className={styles.card}>
            <h2>Register &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by TOBB ETU Kuluçka
      </footer>
    </div>
  )
}
